#!/usr/bin/env bash
set -euo pipefail

FILE="app_pojavlauncher/src/main/java/net/kdt/pojavlaunch/tasks/MinecraftDownloader.java"
python3 - "$FILE" <<'PY'
from pathlib import Path
import sys

p = Path(sys.argv[1])
s = p.read_text(encoding="utf-8")
old = '''                if(isLocalProfile || !isOnline) {\n                    String versionMessage = realVersion; // Use provided version unless we find its a modded instance\n\n                    // See if provided version is a modded version and if that version depends on another jar, check for presence of both jar's .json.\n                    try {\n                        // This reads the .json associated with the provided version. If it fails, we can assume it's not installed.\n                        File providedJsonFile = new File(Tools.DIR_HOME_VERSION + "/" + realVersion + "/" + realVersion + ".json");\n                        JMinecraftVersionList.Version providedJson = Tools.GLOBAL_GSON.fromJson(Tools.read(providedJsonFile.getAbsolutePath()), JMinecraftVersionList.Version.class);\n\n                        // This checks if running modded version that depends on other jars, so we use that for the error message.\n                        File vanillaJsonFile = new File(Tools.DIR_HOME_VERSION + "/" + providedJson.inheritsFrom + "/" + providedJson.inheritsFrom + ".json");\n                        versionMessage = providedJson.inheritsFrom != null ? providedJson.inheritsFrom : versionMessage;\n\n                        // Ensure they're both not some 0 byte corrupted json\n                        if (providedJsonFile.length() == 0 || vanillaJsonFile.exists() && vanillaJsonFile.length() == 0){\n                            throw new RuntimeException("Minecraft "+versionMessage+ " is needed by " +realVersion); }\n\n                        listener.onDownloadDone();\n                    } catch (Exception e) {\n                        String tryagain = !isOnline ? "Please ensure you have an internet connection" : "Please try again on your Microsoft Account";\n                        Tools.showErrorRemote(versionMessage + " is not currently installed. "+ tryagain, e);\n                    }\n                }else {\n                downloadGame(activity, version, realVersion);\n                listener.onDownloadDone();\n                }'''
new = '''                if (isLocalProfile && isOnline) {\n                    // Local/offline accounts do not have Microsoft ownership tokens, but they can\n                    // still download the Minecraft files when the device has Internet access.\n                    // Only the account authentication is offline; the version download is normal.\n                    downloadGame(activity, version, realVersion);\n                    listener.onDownloadDone();\n                } else if (isLocalProfile || !isOnline) {\n                    String versionMessage = realVersion; // Use provided version unless we find its a modded instance\n\n                    // If we are offline, a local account can launch an already-installed version.\n                    try {\n                        File providedJsonFile = new File(Tools.DIR_HOME_VERSION + "/" + realVersion + "/" + realVersion + ".json");\n                        JMinecraftVersionList.Version providedJson = Tools.GLOBAL_GSON.fromJson(Tools.read(providedJsonFile.getAbsolutePath()), JMinecraftVersionList.Version.class);\n                        File vanillaJsonFile = new File(Tools.DIR_HOME_VERSION + "/" + providedJson.inheritsFrom + "/" + providedJson.inheritsFrom + ".json");\n                        versionMessage = providedJson.inheritsFrom != null ? providedJson.inheritsFrom : versionMessage;\n\n                        if (providedJsonFile.length() == 0 || vanillaJsonFile.exists() && vanillaJsonFile.length() == 0){\n                            throw new RuntimeException("Minecraft "+versionMessage+ " is needed by " +realVersion);\n                        }\n\n                        listener.onDownloadDone();\n                    } catch (Exception e) {\n                        String tryagain = !isOnline ? "Please ensure you have an internet connection" : "Please install the selected version while connected to the Internet";\n                        Tools.showErrorRemote(versionMessage + " is not currently installed. "+ tryagain, e);\n                    }\n                } else {\n                    downloadGame(activity, version, realVersion);\n                    listener.onDownloadDone();\n                }'''
if old not in s:
    raise SystemExit("Expected MinecraftDownloader local-account block was not found; refusing to modify the file")
p.write_text(s.replace(old, new, 1), encoding="utf-8")
PY

echo "Local Account Minecraft download flow patched successfully."